# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Firebase"
  lane :firebase_deploy do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID"]
    )
    release_notes = changelog_from_git_commits(
      between: ['HEAD~1', 'HEAD'], 
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })  
    begin
    firebase_app_distribution(
      groups: "alpha",
      release_notes: release_notes,
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      app: ENV['FIREBASE_APP_ID'],
    )
  end
end
end
