name: Build & Deploy Flutter app (Android)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout current code
      - uses: actions/checkout@v3
      # setup flutter for further jobs
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6" # specify the Flutter version
          channel: 'stable'
      # check if flutter is available
      - run: flutter --version

      # install flutter packages
      - name: Install dependencies
        run: flutter pub get

      # verify code formatting 
      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .
      
      # dart linter
      - name: Flutter Analyze
        run: flutter analyze
      
      # run UI tests
      - name: Flutter Tests
        run: flutter test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v3
        with:
          flutter-version: "3.10.6" # specify the Flutter version
      - run: flutter pub get
      - run: flutter build apk # build APK
      - uses: actions/upload-artifact@v3 # upload build artifact
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: release-apk
          path: ./build/app/outputs/flutter-apk/ # download the artifact to this directory
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        working-directory: ./android
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Install Fastlane
        run: |
          gem install --user-install fastlane
          echo 'export PATH="$HOME/.gem/ruby/3.2.2/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Distribute the app through Firebase App Distribution
        working-directory: ./android
        run: |
          bundle exec fastlane firebase_deploy
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_GROUP: ${{ secrets.FIREBASE_GROUP }}
