name: Build & Deploy Flutter app (Android)

on:
  push:
    branches:
      - master

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: "3.10.6" # specify the Flutter version
  #     - run: flutter pub get
  #     - run: flutter test # run Flutter tests

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: "3.10.6" # specify the Flutter version
  #     - run: flutter pub get
  #     - run: flutter build apk # build APK
  #     - uses: actions/upload-artifact@v2 # upload build artifact
  #       with:
  #         name: release-apk
  #         path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - run: cd android
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true  # 'bundle install' will run automatically
      - name: Install Fastlane
        run: |
          gem install --user-install fastlane
          echo 'export PATH="$HOME/.gem/ruby/3.2.2/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Distribute the app through Firebase App Distribution
        run: |
          bundle exec fastlane firebase_deploy
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_GROUP: ${{ secrets.FIREBASE_GROUP }}
